title      : aiworkcn.com
lang       : zh
description: 人工智能 / 企业服务 / 产品应用
copyright  : © 2014 - 2023 aiworkcn.com All Rights Reserved

nav:
 - name: 关于
   link: /blog/
 - name: 人工智能
   link: /blog/aicode/
 - name: En
   link: /blog/about/
