title      : aiworkcn.com
lang       : zh
description: 人工智能 / 企业服务 / 产品应用
copyright  : © 2014 - 2023 aiworkcn.com All Rights Reserved

nav:
 - name: me
   link: /blog/
 - name: (AI)
   link: /blog/aicode/
 - name: en
   link: /blog/about/
